FROM python:3.12.3-alpine

WORKDIR /app

RUN pip install poetry==1.8.3
RUN poetry config virtualenvs.create false

COPY ./src ./

RUN poetry install --no-root --no-dev

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0"]